### ISSUE TITLE
Missing SkipSelf Option on GenerateAngularModel Attribute

### ISSUE THREAD

**Issue by joachim-heck** [KY-Programming/generator#17]
Hey Kai, I'm missing out the quite useful SkipSelf operator which was available in the old Generator.json configuration - Is there a way to configure it in the new 5.0 Version?

**Comment by ky-one** [comment]
Hi Joachim,
the GenerateAngularModelAttribute was designed to generate one model for angular.
Please try to use GenerateIndexAttribute. See the [documentation](https://generator.ky-programming.de/reflection/examples/generate-multiple-models).

Please provide feedback, if your problem is solved or not.

Regards Kai

**Comment by ky-one** [comment]
Added [GenerateAngularIndexAttribute](http://generator.ky-programming.de/angular/overview/api#GenerateAngularIndexAttribute) to add the missing Object.assign(...) in constructor.

See [documentation](http://generator.ky-programming.de/angular/annotations/model#index) for all informations

Will be part of the next release
